# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
  Harmony\Bundle\WebProfilerBundle\DataCollector\HarmonyCollector:
    arguments: ['@service_container']
    tags:
      - { name: data_collector, template: "@HarmonyWebProfiler/Collector/harmony.html.twig", id: "harmony.collector" }